# Lliurex chboot
Luis Garcia
:compat-mode:
:toc:
:icons: font
:toc-title: Index
:toclevels: 3
:doctype: article
:experimental:
:icons: font
:sectanchors:
:sectlinks:
:sectnums:
:imagesdir: ./images

=== Context

Des de les primeres versions de LliureX, l'aula, centra i models de
centre llest gerència inclosa, actualitza i eines de configuració per
als ordinadors del centre que ha estat amplament utilitzat per tècnics
de suport (SAI), ICT coordinadors i altre personal amb responsabilitats
de gerència per als ordinadors dels centres. es podrien utilitzar
Aquestes utilitats també centralment des dels servidors del centre.
Aquestes aplicacions ús fet de característiques com configuració i bota
de xarxa serveis (DHCP, DNS, PXE) allò va ser #abastar directament en el
centre LliureX servidors.

Després de l'emissió de lliurex23, una visió molt més corporativa de
l'estació de treball dels centres educatius ha estat introduït. Els
objectius majors d'aquest model nou són per augmentar seguretat i
facilitar una gerència centralitzada de l'EL infraestructura. En ordena
per aconseguir aquests objectius, les transformacions importants han
tingut lloc dins l'EL infraestructura de tots els centres educatius en
la Comunitat valenciana. Aquests canvis afectar l'arquitectura i
característiques de les xarxes i comunicacions així com els detalls de
configuració de l'equipament d'ordinador.

LliureX models de gerència van ser dissenyats en un context anterior que
era molt diferent des de l'actual EL Paradigma d'infraestructura. En
particular, les capacitats per a la xarxa que xuta (en ordena per
aconseguir operacions de xarxa mentre clonant ordinador o instal·lació)
ha estat dràsticament reduït i és ja no viable en pràctica a
conseqüència del centraliced gerència de DHCP i DNS des del DGTIC
(quines marques ella impossible de configurar paràmetres de xarxa ad hoc
des de LLiureX ordinadors). Per acabar-ho d'adobar, els paràmetres de
seguretat de l'ordinador (SecureBoot, contrasenya de BIOS ... ) difícil
no només per xutar des de xarxa però també des de qualssevol mitjans de
comunicació desmuntables, fent reinstalling o actualitzant l'equipament
una missió real impossible.

LliureX chboot intenta mitigar limitacions de bota de la xarxa, i
proporciona un entorn alternatiu es pot utilitzar allò per instal·lar,
actualitza o clona LliureX ordinadors des d'imatges o mitjans de
comunicació d'instal·lació. Camp de casos de l'Ús des d'instal·lar
ordinadors individuals per córrer desplegaments massius amb eines mentre
clonezilla o LliureX obert-sysclone

=== Resum

Lliurex chboot respon a LliureX ch(ange) bota, i inclou un conjunt
d'eines per configurar modes de bota alternativa per LliureX ordinadors.

El (simple) i la idea major és per utilitzar una segona partició del
disc dur (etiquetat `chboot`) per xutar un sistema alternatiu. evitant
la necessitat de configurar ordinadors per xutar des de xarxa o mitjans
de comunicació desmuntables per actuar operacions com:

* instal·lació d'un nou OS versió
* reinstallation des d'una imatge de disc de la recuperació

LliureX chboot pot ser corregut dins un sol una xarxa ordinador aïllat,
però en combinació amb altre LliureX eines, pot ser també utilitzat en
entorns de laboratoris de l'ordinador per distribuir configuracions i
imatges de disc per actuar desplegaments massius (des d'una adreça d'IP
sabuda per endavant).

El va incloure configuracions, permet modes de bota diferent:

* self (i unattended) clonezilla cas per restaurar imatge de disc des de
chboot partició
* self (i unattended) clonezilla cas per restaurar des de contacta dins
LliureX entorn de laboratori de l'ordinador
* automatitzat clonezilla servidor per a desplegaments massius
* corregut clonezilla imatge en mode interactiu
* corregut interactiu LliureX imatge d'instal·lació

=== Detalls de procediment de la Bota

Per configurar opcions de bota alternativa, LliureX chboot depèn damunt
*_UEFI Gerent de Bota i grub_*.

imatge::chboot-xuta.svg[]

Quan un ingrés de bota nou és creat, chboot genera:

* Un *_UEFI ingrés de bota_*.

____
Aquest ingrés és availabe per UEFI Gerent de Bota, però chboot *_no
inclou ell en l'ordre de bota_* però conjunts l'UEFI ` BootNext` `NVRAM`
variable, i (opcionalment) provoca un sistema reboot.
____

* La carpeta *_de directori associada dins l'EFI Partició de Sistema_*
per llançar grub

____
Quan creant aquest directori, chboot els escàners actuals EFI dividir i
buscar `EFI/lliurex-25/`, `EFI/lliurex-23/` o `EFI/ubuntu/` carpetes (en
aquell ordre) i usos el primer matx com a plantilla per copiar fitxers
per l'ingrés nou. El `grub.cfg` el fitxer és reescrit per proporcionar
un appropiated grub configuració de prefix per l'ingrés de bota nou.
____

* Un *_grub directori de bota dins el chboot partició_* amb els fitxers
de bota requerits i grub configuració

LliureX chboot usos exactament el mateix nom per l'EFI carpeta i l'UEFI
ingrés de bota. Aquests noms són prefixats amb `chboot_`. En aquest
moment, chboot abasta només un xuta ingrés amb un nom fix
(`chboot_lliurex`) malgrat tot del nom d'imatge concret per xutar.
Aquesta estratègia impedeix la proliferació d'ingressos innecessaris
dins l'UEFI Gerent de Bota. Tanmateix, dins el chboot partició, cap
prefix és utilitzat per als noms dels directoris dels ingressos
diferents, i cadascú u té el seu directori “de” bota propi dins del seu
subdirectori. L'UEFI càrregues d'ingrés de la bota `shimx64.efi` fitxer
per proporcionar compatibilitat amb configuracions de Bota Segura.

=== El chboot partició de disc

LliureX chboot requereix una partició de disc dedicada. s'hauria de
posar mida de Partició segons les imatges de disc o iso arxiva desitges
utilitzar. El default mida quan corrent lliureX instal·lador dins OEM el
mode és 12 GB, prou per acomodar una imatge d'ISO de Clonezilla i el
LliureX instal·lador a l'encop.

LliureX chboot requereix l'ús d'un rètol de disc concret (`chboot`) a
correctament identificar el chboot partició. La partició de disc dura
mut ser etiquetat utilitzar e2label, tune2fs o utilitats de disc
alternatiu. Per assegurar l'operació, el `chboot` s'ha de mostrar el
rètol correctament quan utilitzant `blkid` o `lsblk` ordres, i el disc
partitin ha de ser accesible sota `/dev/disc/per-etiqueta/chboot` camí.

El default sistema de fitxers per chboot la partició és `ext4`, però
qualsevol altre sistema de fitxers recolzat per `grub` podria ser
utilitzat.

LliureX chboot proporciona l'appropiate `systemd configuració` de mont
per accedir chboot partició sota `/chboot` punt de mont, així que ell no
per ser afegit a `fstab` fitxer.

=== chboot estructura de directori

LliureX chboot crea l'estructura de directori següent, on `/chboot` és
el punt de mont de la partició:

....
/chboot
└── lliurex-chboot
    ├── imgs
    ├── isos
    └── srcs
        ├── CARPETA_d'INGRÉS_1
        ...
        └── CARPETA_d'INGRÉS_n
....

* `lliurex-chboot`: Directori de Base per tot el LliureX chboot
material.
** `lliurex-chboot/imgs`: clonezilla directori d'imatges
** `lliurex-chboot/isos`: directori per bootable iso fitxers
** `lliurex-chboot/srcs`: chboot bootable (font) configuracions

=== chboot ingressos (o configuracions de font)

Un chboot ingrés (aka configuració de font) és una carpeta de directori
que conté tota la informació necessari de configurar una opció de bota
alternativa. El `chbootmgr` l'eina busca ingressos sota
lliurex-chboot/srcs carpeta.

____
NOTA: El chboot la partició no és automàticament muntat a startup, així
que per instal·lar chboot els ingressos des d'un Debian empaqueten, no
és segura de provar per caure els fitxers directament a `/chboot`. El
camí correcte és per posar-los en un altre camí i utilitza
`chbootmgr instal·la` dins `postinstall` o altre maintainer guions.
____

Això és un exemple del chboot arbre d'ingressos:

....
/chboot
└── lliurex-chboot
    └── srcs
        ├── INGRÉS_FOLDER1
        │   ├── chboot.cfg
        │   ├── hams
        │   └── de bota
        │       ├── instal·lar
        │       ├── uninstall
        │       ├── l'escac
        │       ├── prepara
        │       ├── lliure_dalt
        │       └── mk_grub
        ├── INGRÉS_FOLDER2
            .....
....

Chboot els ingressos són manged per chbootmgr eina. La figura següent
resumeix les opcions més importants.

imatge::chboot-ingrés-vida-cyle.svg[]

==== Carpetes i fitxers Obligatoris per a cada configuració de font

* `chboot.cfg` (arxiva): Això inclou descripció i altra informació sobre
l'ingrés. L'estructura i la sintaxi del fitxer és similar a
`debian/fitxers` de control.
* `bota` (dir): Aquest directori ha d'incloure tots els fitxers
necessaris per xutar l'ingrés, com la /bota/grub carpeta d'un estàndard
linux sistema (eg. vmlinuz, initrd, squashfs fitxers, configuracions
...). Quan el chboot l'ingrés és activat, chboot crea un grub
configuració dins l'EFI partició aquell espera un `grub.cfg` fitxer en
aquesta carpeta.
* `hams` (dir): La carpeta d'hams ha d'incloure el següent executables:
** `instal·la`: El guió és un "oneshot" guió, i és anomenat només una
vegada, només per copiar/instal·lar l'ingrés al chboot partició el
primer cop. Rep el camí ple de directori de bota tan primer argument
(`/$CHBOOT_MONT/$CHBOOT_SRCDIR/$bota_de/NOM de l'INGRÉS`). L'estat de
sortida del guió és silenty va ignorar.
** `uninstall`: Anomenat abans que eliminació del chboot ingrés.
** `escac`: LliureX chboot curses aquest guió per assegurar que la
configuració de font és llesta d'utilitzar i pot ser arrencat. És només
un guió de prova per comprovar la presència de va requerir fitxers i
configuracions sense provar per fixar qualsevol cosa. El guió rep el
camí ple del seu directori de bota
(`/chboot/lliurex-chboot/srcs/bota_de/CARPETA de l'INGRÉS`) tan primer
argument. Un no zero surt l'estat indica que l'ingrés no és a punt, i la
sortida estàndard és mostrada com una explicació del problema.
** `prepara`: L'ús pretès d'aquest guió és per
descarregar/instal·lar/generar *_TOT_* el va requerir fitxers per rebre
el chboot ingrés a punt per xutar (excepte el grub.cfg fitxer, el qual
és creat més tard per córrer `mk-grub`) . Com en cas anterior, el primer
argument del guió és el camí ple del seu directori de bota, però pot
utilitzar qualsevol classe d'arguments addicionals arbitraris. L'estat
de sortida i la sortida estàndard d'aquest guió és mostrada a usuari
després que execució, però l'estat de preparació del chboot l'ingrés és
determinat pel resultat d'execució de `comprova` dicta.
** `lliure_dalt`: Aquest guió no és automàticament executat per chboot
per abastar ingressos, però pot ser invocat per usuari en ordena per
reduir disc ús espacial (eg. per eliminar descarregat isos o fitxers
d'imatge). Podria ser considerada com l'opposit del configurar guió.
** `mk_grub`: La sortida estàndard d'aquest guió és utilitzada per
generar el grub.cfg fitxer dins el chboot partició. Funciona en un camí
similar als guions dins /etc/grub.d/.

==== paràmetres i variables d'entorn per chboot execució de guió

Tots guions d'ham tenir accés a les variables d'entorn següents:

===== Camins de Sistema

* `CHBOOT_MONT`: punt de mont per chboot partició (defaults a
`/chboot`). La resta de variables d'entorn és parentes a aquest punt de
mont per plasmar camins a dins el chboot partició.

===== Chboot partició camins relatius

* `CHBOOT_BASEDIR`: directori de base per tot el chboot material
(defaults a `/lliurex-chboot`)
* `CHBOOT_ISODIR` : iso carpeta de fitxers (defaults a
`$CHBOOT_BASEDIR/isos`)
* `CHBOOT_IMGDIR` : directori per emmagatzemar clonezilla imatges
(defaults a `$CHBOOT_BASEDIR/imgs`)
* `CHBOOT_SRCDIR` : chboot directori de base de configuracions de font
(defaults a `$CHBOOT_BASEDIR/srcs`)
* `CHBOOT_BOOTDIR`: aquests amfitrions de directori el grub directori de
bota per chboot fonts, agrada `/carpeta` de bota en un estàndard linux
sistema (defaults a `$CHBOOT_BASEDIR/bota`)

===== Chboot partició info

* `CHBOOT_UUID`: `UUID` de chboot partició
* `CHBOOT_PART`: chboot dispositiu de partició del disc

=== chbootmgr

Això és l'eina de gerència per chboot. La sintaxi i les opcions
disponibles són:

....
Ús: chbootmgr {configura|unconfigure|mont|umount|llista}
       chbootmgr espectacle CHBOOT_INGRÉS
       chbootmgr prepara CHBOOT_INGRÉS [PREPARA PARÀMETRES OPCIONALS ...]
       chbootmgr bota-pròxim CHBOOT_INGRÉS
       chbootmgr bota [+SECUNDA] CHBOOT_INGRÉS
....

=== Paquets Binaris

* *lliurex-chboot*
