#!/bin/sh

GRUB_DISABLE_RECOVERY=true
GRUB_DISABLE_SUBMENU=true
[ "$CHBOOT_TITLE" ] || CHBOOT_TITLE="Unattended LliureX 25 install from DISK image"
CHBOOT_URL_OPTION=""
if [ "$CHBOOT_URL" ] ; then
	CHBOOT_URL_OPTION="chb.url=$CHBOOT_URL"
fi

# . "$pkgdatadir/grub-mkconfig_lib"

BOOT_DIR="/boot"
CHBOOT_DIR="/chboot"
CHBOOT_INITRD=""

get_disk_id(){
	MOUNT_POINT="$1"
	ID_TYPE="$2"
	lsblk -nplo MOUNTPOINT,$ID_TYPE |sed -ne "\%$MOUNT_POINT\s%{s%^.*\s%%;p}"
}

get_uuid(){
	MOUNT_POINT="$1"
	ID_TYPE="UUID"
	get_disk_id "$MOUNT_POINT" "$ID_TYPE"
}

get_partuuid(){
	MOUNT_POINT="$1"
	ID_TYPE="PARTUUID"
	get_disk_id "$MOUNT_POINT" "$ID_TYPE"
}


# find chboot initrd
CHBOOT_INITRD="$(ls -1 "$BOOT_DIR" | grep "^initrd_chboot.img" |tail -1)"
[ "$CHBOOT_INITRD" ] || exit 0

KERNEL_VERSION="${CHBOOT_INITRD#*-}"

# find chboot partition
CHBOOT_BY_LABEL="/dev/disk/by-label/chboot"
[ -e "$CHBOOT_BY_LABEL" ] || exit 0
CHBOOT_PART="$(readlink -f "$CHBOOT_BY_LABEL")"
CHBOOT_UUID="$(lsblk -nplo UUID "$CHBOOT_PART")"

# find current root partition
ROOT_UUID="$(get_uuid "/")"
ROOT_PARTUUID="$(get_partuuid "/")"
if [ -z "$ROOT_UUID" ] || [ -z "$ROOT_PARTUUID" ] ; then
	exit 0
fi

# find efi partition
EFI_UUID="$(get_uuid "/boot/efi")"
[ "$EFI_UUID" ] || exit 0

cat <<EOF
set timeout=10
search --no-floppy --fs-uuid --set=root ${CHBOOT_UUID}

menuentry 'CHBOOT: ${CHBOOT_TITLE} (${KERNEL_VERSION})' --class lliurex --class gnu-linux --class gnu --class os \$menuentry_id_option 'gnulinux-${KERNEL_VERSION}-advanced-${ROOT_UUID}' {
        recordfail
        load_video
        gfxmode \$linux_gfx_mode
        insmod gzio
        if [ x\$grub_platform = xxen ]; then insmod xzio; insmod lzopio; fi
        insmod part_gpt
        insmod ext2
        search --no-floppy --fs-uuid --set=root ${CHBOOT_UUID}
        echo    'Loading Linux ${KERNEL_VERSION} for CHBOOT RESTORE ...'
        linux   /boot/vmlinuz-${KERNEL_VERSION} root=PARTUUID=${ROOT_PARTUUID} ro boot=chboot chb.uuid=${ROOT_UUID} chb.efi=UUID=${EFI_UUID} chb.dev=UUID=${CHBOOT_UUID} chb.dir=${CHBOOT_DIR} $CHBOOT_URL_OPTION net.ifnames=0 rw $vt_handoff
        echo    'Loading initial ramdisk ...'
        initrd  /boot/${CHBOOT_INITRD}
}
EOF

