#!/bin/sh
DEST_DIR="$1"
if [ -z "$DEST_DIR" ] || [ ! -d "$DEST_DIR" ] ; then
	echo "Invalid destination directory" >&2
	exit 1
fi
DEST_FILE="$DEST_DIR/lliurex-local-users"
UID_MIN=1000
UID_MAX=30000
USERS_BLACK_LIST="estudiant nobody guest-user"

get_local_users(){
	UID_MIN="$UID_MIN" UID_MAX="$UID_MAX" awk -F: '$3>=ENVIRON["UID_MIN"] && $3<=ENVIRON["UID_MAX"] {print $1":"$3}' /etc/passwd
}



cat /etc/passwd |sort -n -t ":" -k 3 

tar -C /etc/lliurex-auto-upgrade/ -cvzf "DEST_FILE" tags/
